dollar_amount_buy_lost: 0.3100799999999999
dollar_amount_buy_won: 0.19168600000000013
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 3.0
n_buy_won: 5.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 29.0
