dollar_amount_buy_lost: 18.792500000000018
dollar_amount_buy_won: 40.20749999999997
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 2.0
n_buy_won: 4.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 36.0
