dollar_amount_buy_lost: 53.66500000000002
dollar_amount_buy_won: 48.95249999999997
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 6.0
n_buy_won: 5.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 60.0
