dollar_amount_buy_lost: 14.215000000000003,
dollar_amount_buy_won: 0
dollar_amount_short_lost: 0
dollar_amount_short_won: 0
n_buy_lost: 1
n_buy_won: 0
n_short_lost: 0
n_short_won: 0
n_total_days_in_trades: 7.0
