buy_entry_price: 82.9775
buy_has_crossed_mean: 0.0
mode: buy
position_entry_date: '2022-02-21 00:00:00'
short_entry_price: 0.0
short_has_crossed_mean: 0.0
stop_loss_pct: 0.1
stop_loss_price: 77.79825
