dollar_amount_buy_lost: 18.792500000000018
dollar_amount_buy_won: 37.559999999999974
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 2.0
n_buy_won: 3.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 30.0
