buy_entry_price: 192.5475
buy_has_crossed_mean: 0.0
mode: buy
position_entry_date: '2021-11-26 00:00:00'
short_entry_price: 0.0
short_has_crossed_mean: 0.0
stop_loss_pct: 0.1
stop_loss_price: 173.68425
