dollar_amount_buy_lost: 14.215000000000003
dollar_amount_buy_won: 10.477499999999992
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 1.0
n_buy_won: 1.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 13.0
