dollar_amount_buy_lost: 23940.03
dollar_amount_buy_won: 38239.399999999994
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 16.0
n_buy_won: 7.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 135.0
