dollar_amount_buy_lost: 1692.6800000000005
dollar_amount_buy_won: 2622.0299999999993
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 16.0
n_buy_won: 19.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 236.0
