dollar_amount_buy_lost: 1.0099
dollar_amount_buy_won: 1.608224
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 13.0
n_buy_won: 8.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 104.0
