dollar_amount_buy_lost: 44.682500000000005
dollar_amount_buy_won: 66.60499999999998
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 11.0
n_buy_won: 8.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 89.0
