dollar_amount_buy_lost: 35.495000000000005
dollar_amount_buy_won: 47.37749999999998
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 10.0
n_buy_won: 7.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 80.0
