dollar_amount_buy_lost: 54.352500000000006
dollar_amount_buy_won: 105.50749999999996
dollar_amount_short_lost: 0.0
dollar_amount_short_won: 0.0
n_buy_lost: 12.0
n_buy_won: 11.0
n_short_lost: 0.0
n_short_won: 0.0
n_total_days_in_trades: 114.0
