prediction_params:
    bollinger_window: 10
    no_of_std: 1.5
    lookback_window: [15, 30, 90]
    prediction_n_days: 14
    model_name: ["TCN", "NBEATS"]
    work_dir: "/mnt/shared-storage"
hyperparameters_tcn:
    dropout: 0.10
    random_state: 0
    dilation_base: 2
    kernel_size: 14
    num_filters: 7
    num_layers: 7
    weight_norm: True
    epochs: 55
hyperparameters_nbeats:
    random_state: 0
    num_blocks: 5
    layer_widths: 256
    epochs: 7
