prediction_params:
    bollinger_window: 7
    no_of_std: 1.5
    lookback_window: 15
    prediction_n_days: 14
    additional_dfs: [bitcoin_df]
    stop_loss_pct: .05,
    model_name: ["TCN", "NBEATS"]
hyperparameters_tcn:
    dropout: 0.10
    random_state: 0
    dilation_base: 2
    kernel_size: 3
    num_filters: 6
    num_layers: 6
    weight_norm: True
    epochs: 1
hyperparameters_nbeats:
    random_state: 0
    num_blocks: 4
    layer_widths: 256
    epochs: 1


