btc:
  buy_entry_price: 0
  buy_has_crossed_mean: false
  mode: no_position
  position_entry_date: None
  short_entry_price: 0
  short_has_crossed_mean: false
  stop_loss_pct: 0.08
  stop_loss_price: 0
eth:
  buy_entry_price: 0
  buy_has_crossed_mean: false
  mode: no_position
  position_entry_date: None
  short_entry_price: 0
  short_has_crossed_mean: false
  stop_loss_pct: 0.08
  stop_loss_price: 0
